club_manager/urls.py
from django.contrib import admin
from django.urls import path
from club import views as club_views

urlpatterns = [
    path("club/<slug:slug>", club_views.club_detail_view, name="club_detail_view"),
    path('admin/', admin.site.urls),
    path("", club_views.index_view, name="index"),
]

club/models.py
import uuid

from django.db import models

from model_utils.models import TimeStampedModel
from django.utils.text import slugify


class Club(TimeStampedModel):
    uuid = models.UUIDField(primary_key=True,
                            default=uuid.uuid4,
                            editable=False)
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=50)

    def __str__(self):
        return self.name

    def save(self,
             force_insert=False,
             force_update=False,
             using=None,
             update_fields=None):
        self.slug = slugify(self.name)
        if update_fields is not None and "name" in update_fields:
            update_fields = {"slug"}.union(update_fields)
        super().save(
            force_insert=force_insert,
            force_update=force_update,
            using=using,
            update_fields=update_fields,
        )

matches/models.py
from django.db import models
from model_utils.models import TimeStampedModel


class Game(TimeStampedModel):
    """Model a notion of a Game.
    """
    home_team = models.ForeignKey("members.Team", on_delete=models.PROTECT, related_name='home_games')
    away_team = models.ForeignKey("members.Team", on_delete=models.PROTECT, related_name='away_games')
    date = models.DateField()
    place = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.home_team} - {self.away_team}"


class Call(TimeStampedModel):
    
    class Status(models.TextChoices):
        AWAITING_REPLY = 'awaiting', "Awaiting reply"
        ACCEPTED = 'accepted', "Accepted"
        REFUSED = 'refused', "refused"

    game = models.ForeignKey(Game, related_name="calls", on_delete=models.CASCADE)
    member = models.ForeignKey("members.MemberTeam", related_name="calls", on_delete=models.CASCADE)
    status = models.CharField(max_length=20, choices=Status.choices, default=Status.AWAITING_REPLY)

    def __str__(self):
        return f"{self.game} {self.member}"

members/models.py
import uuid
from django.db import models

from model_utils.models import TimeStampedModel
from django.utils.translation import gettext_lazy as _


class Role(models.TextChoices):
    PLAYER = 'PLAYER', _('Player')
    COACH = 'COACH', _('Coach')


class Team(TimeStampedModel):
    name = models.CharField(max_length=100)
    club = models.ForeignKey("club.Club", related_name="teams", on_delete=models.PROTECT)

    def __str__(self):
        return f"{self.club} {self.name}"


class Member(TimeStampedModel):
    uuid = models.UUIDField(default=uuid.uuid4, editable=False)
    full_name = models.CharField(max_length=250)
    team = models.ManyToManyField(Team, through="MemberTeam", related_name="members")

    def __str__(self):
        return self.full_name


class MemberTeam(TimeStampedModel):
    """A member can belong to many teams and a team can have many members"""

    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    role = models.CharField(max_length=10,
                            choices=Role.choices,
                            default=Role.PLAYER)

    def __str__(self):
        return f"{self.team} - {self.member}"

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

club/views.py
from django.shortcuts import render, get_object_or_404
from club.models import Club  # importer le modele pour l'utiliser plus tard
from matches.models import Game
from club.use_cases import get_unique_members, get_games


def index_view(request):
    """Index view welcoming our users
    """
    clubs = Club.objects.all()  # on récupère tous les clubs de notre base
    
    # le contexte est transmis au template
    context = {
        "clubs_list": clubs
    }
    return render(request, "club/index.html", context=context)


def club_detail_view(request, slug):
    """Display important information about a specific club"""
    club = get_object_or_404(Club, slug=slug)
    
    members = get_unique_members(club)

    games = get_games(club)
    
    context = {"club": club, "members_list": members, "teams": club.teams.all(), "team_count": club.teams.count(), "member_count": len(members), "games_list":  games}
    return render(request, "club/detail.html", context=context)

matches/views.py
from django.shortcuts import render

# Create your views here.

members/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
<!doctype html>
<html class="no-js" lang="">

<head>
  <meta charset="utf-8">
  <title></title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <meta property="og:title" content="">
  <meta property="og:type" content="">
  <meta property="og:url" content="">
  <meta property="og:image" content="">

  <link rel="icon" href="/favicon.ico" sizes="any">
  <link rel="icon" href="/icon.svg" type="image/svg+xml">
  <link rel="apple-touch-icon" href="icon.png">

  <link rel="stylesheet" href="css/normalize.css">
  <link rel="stylesheet" href="css/style.css">

  <link rel="manifest" href="site.webmanifest">
  <meta name="theme-color" content="#fafafa">
</head>

<body>
 
  <h1>Club Manager</h1>

{% block content %}
{% endblock %}  
    
</body>

</html>

templates/club/detail.html
{% extends "base.html" %}

{% block content %}

<a href="{% url 'index' %}">Home</a>

<h2>Club : {{ club }}</h2>

Ce club a {{ team_count }} équipes et {{ member_count }} membres
Liste des membres

{% for team in teams %}
<ul>
    {{ team }}
    
    <ul>
        {% for member in team.memberteam_set.all %}
            <li>{{ member.member }}</li>
        {% endfor %}
    </ul>
</ul
{% endfor %}

<h2>Matchs</h2>
<ul>
{% for game in games_list %}
    <li>{{ game.date }}</li>
{% empty %}
    <li>There are no games scheduled</li>
{% endfor %}
</ul>

{% endblock %}

templates/club/index.html
{% extends "base.html" %}

{% block content %}

Liste des clubs

<ul>
{% for club in clubs_list %}
    <li><a href="{% url 'club_detail_view' club.slug %}">{{ club }}<a></li>
{% endfor %}
</ul>

{% endblock %}